### ISSUE TITLE
error in models/GLMP.py

### ISSUE THREAD

**Issue by luweishuang** [jasonwu0731/GLMP#1]
in models/GLMP.py，F1_score used without definition.
also, I confused about data/KVR/train.txt  + dev.txt + test.txt, how does they come from and why they are processed in that format?

**Comment by jasonwu0731** [comment]
Thanks for the reminding. I added the line 261 "F1_score = F1_pred / float(F1_count)" to define the F1 score. 

For data processing and cleaning, it is the same as the previous work [Mem2Seq](https://github.com/HLTCHKUST/Mem2Seq). The format is to mimic the [bAbI dialogue](https://research.fb.com/downloads/babi/) format.
