### ISSUE TITLE
Will it work with real data?

### ISSUE THREAD

**Issue by iuria21** [jasonwu0731/GLMP#2]
Hi, first thanks four publishing your job, it's amazing. This is not a bug, but a question:
Do you think that this kind of models are ready to work with real data? Say I have real transcriptions for a Airway company, where the agent and the client are talking with a goal (buy tickets, do check-in, etc). Will the model be able to simulate the agent's sentences in a correct way or is it so complicated yet? 
Do you think that some end-to-end model it's ready to do it at the moment? Or is the only way to label intents and entities like in Dialogflow, etc.?

Thanks for your opinion!

**Comment by jasonwu0731** [comment]
Hello @basque21 

Thank you for your interests in our work. You point out a good issue. If you check the appendix in the paper, you will find a short discussion about this. Let me provide the paper link and also quote the paragraph below.

https://arxiv.org/pdf/1901.04713.pdf

> One of the reviewers suggested us to compare our work to some existing dialogue framework such as PyDial To the best of our knowledge, in the PyDial framework, it requires to have the dialogue acts labels for the NLU module and the belief states labels for the belief tracker module. The biggest challenge is we do not have such labels in the SMD and bAbI datasets. Moreover, the semi tracker in PyDial is rule-based, which need to re-write rules whenever it encounters a new domain or new datasets. Even its dialogue management module could be a learning solution like policy networks, the input of the policy network is still the hand-crafted state features and labels. Therefore, without the rules and labels predefined in the NLU and belief tracker modules, PyDial could not learn a good policy network. Truly speaking, based on the data we have (not very big size) and the current state-of-the-art machine learning algorithms and models, we believe that a well and carefully constructed task-oriented dialogue system using PyDial in a known domain using human rules (in NLU and Belief Tracker) with policy networks may outperform the end-to-end systems (more robust). However, in this paper, without additional human labels and human rules, we want to explore the potential and the advantage of end-to-end systems. Besides easy to train, for multi-domain cases, or even zero-shot domain cases, we believe end-to-end approaches will have better adaptability compared to any rule-based systems.
