### ISSUE TITLE
ZeroDivisionError: float division by zero when evaluating on BABI

### ISSUE THREAD

**Issue by isaacmg** [jasonwu0731/GLMP#3]
Hi, thanks for the code posting the code for the paper.

I did have an issue when training on BABI. When running the following command 
`python myTrain.py -lr=0.001 -l=1 -hdd=128 -dr=0.2 -dec=GLMP -bsz=8 -ds=babi -t=1`
 
It throws the following error: 
```Epoch:0
L:0.58,LE:0.09,LG:0.38,LP:0.10: 100% 753/753 [01:34<00:00,  7.82it/s]
STARTING EVALUATION
100% 61/61 [00:13<00:00,  4.57it/s]
Traceback (most recent call last):
  File "myTrain.py", line 49, in <module>
    acc = model.evaluate(dev, avg_best, early_stop)
  File "/content/GLMP/models/GLMP.py", line 261, in evaluate
    F1_score = F1_pred / float(F1_count)
ZeroDivisionError: float division by zero
```

Just glancing at the code it seems that F1 score is initialized to zero and is not changed for anything but the KVR dataset.

**Comment by jasonwu0731** [comment]
Thanks for pointing out this issue. Move that line inside this "if" function will be fine.
>> if args['dataset'] == 'kvr':
