### ISSUE TITLE
API calls

### ISSUE THREAD

**Issue by mlmu** [jasonwu0731/GLMP#5]
Hi, first of all - thank you for your great work and for sharing the code!

Would you please help me with a following question: According to the task formulation for the bAbI dataset, system should make API calls to derive information on smth. for instance, on restaurants, correct? If I understood it correctly, GLMP also able to deal with it, however I failed to find a place in a code, where it actually happens.
Would you please, tell whether GLMP makes API calls and if yes, on which position in a code it happens? One more question: Do you think it is possible to replace this kind of API calls with calls to ElasticSearch?

I would be very grateful for your answers!

Many thanks in advance!

**Comment by jasonwu0731** [comment]
Hi @mlmu 

The API call you mentioned in bAbI dialogue is considered as possible system responses. Therefore, there is no specific code part related to API call, instead, the api call is directly generated by our model as a response.

Replacing API call with ElasticSearch is possible, in the end, what returns from the KB is the key.

Hope this help.
