### ISSUE TITLE
Trainning for each task

### ISSUE THREAD

**Issue by Toan-Do** [jasonwu0731/GLMP#6]
Hello, thank you for sharing your code.

I have 2 question, please help me answer it: 
1. You train a new model for each task or you use a trained model in previous task and finetune it on another task?

2. To build a full coversation chat, i should use model trained on task 5, right?

Thank you for your answer.

**Comment by jasonwu0731** [comment]
hi @dvtoan97 

1. In the experiments listed on my paper, I trained each task independently.
2. yes that one is the full dialogue task.

Hope this help.
