### ISSUE TITLE
How to set the hyper-parameters

### ISSUE THREAD

**Issue by zengyazy** [jasonwu0731/GLMP#9]
Hi,
How did you set the hyper-parameters to get the results in the paper？I try to set hidden size to 128， and hop K is set  to 3，but the results are far from those in the paper.Below is the result of my running：
ACC SCORE: 0.1227
F1 SCORE:    0.5788
CAL F1:        0.7344
WET F1:       0.5486
NAV F1:       0.5058

I try to set hidden size to 256, even the result is not as good as the result with a hidden size of 128.How do you set the hyper-parameters?

**Comment by scoyer** [comment]
I can't reproduce the results of the paper either.

**Comment by jasonwu0731** [comment]
Hi 

Please check this issue #8 and let me know if you have any questions for training.

**Comment by jasonwu0731** [comment]
Hi,

You can check this issue #8 for more information. We had released the trained model reported in the paper [here](https://drive.google.com/file/d/19_choYhDq2CGdhIQzL56Q-CD15T2YALn/view?usp=sharing). Hope this help.

```
ACC SCORE:	0.12267657992565056
F1 SCORE:	0.5996873409698522
	CAL F1:	0.6956311078262298
	WET F1:	0.6257885219093696
	NAV F1:	0.5298233847529625
BLEU SCORE:	14.79
```

**Comment by zengyazy** [comment]
@jasonwu0731 

It hepls a lot. Thank you very much!
